### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by scottchiefbaker**
Update the README and MarqueeText example so they're more friendly for amateurs (like me)

### CODE REVIEW

**Comment by bartoszbielawski** [comment]
Thanks :)

**Comment by scottchiefbaker** [comment]
Would you be interested in me updating the other examples so they're all consistent? I can whip up another PR if it's something you think would be helpful.

**Comment by scottchiefbaker** [comment]
Are there any cases where this library would be used that are NOT 8x8 segments? If so it probably would just be easier to define a number of segments.

Also in the [old code](https://github.com/bartoszbielawski/LEDMatrixDriver/commit/ec256a4daf769a8a8589c5f66cf85c3a40ee8732#diff-3847aa2da9c5177e210fb1f6177c4aebL10) it talks about `32x8 = 31x7`? I tried the example with both and they seemed to work fine? For sanity I think we should standardize on 32x8 (and if need be change it in the library itself).

**Comment by bartoszbielawski** [comment]
> Are there any cases where this library would be used that are NOT 8x8 segments? If so it probably would just be easier to define a number of segments.

No that I know of. You could use it in 7seg mode but then it uses a different API. 

> Also in the old code it talks about 32x8 = 31x7? I tried the example with both and they seemed to work fine? For sanity I think we should standardize on 32x8 (and if need be change it in the library itself).

I'm pretty sure this constant wasn't even used.  `drawSprite()` calls have the height hard coded as 8.

**Comment by bartoszbielawski** [comment]
> Are there any cases where this library would be used that are NOT 8x8 segments? If so it probably would just be easier to define a number of segments.

No that I know of. You could use it in 7seg mode but then it uses a different API. 

> Also in the old code it talks about 32x8 = 31x7? I tried the example with both and they seemed to work fine? For sanity I think we should standardize on 32x8 (and if need be change it in the library itself).

I'm pretty sure this constant wasn't even used.  drawSprite() calls have the height hard coded as 8.

**Pull request merged**
