### PR TITLE
Support for 7-segment displays.

### PR DESCRIPTION
**Pull request by Sthing**
Hi Bartosz,

Thank you for the library.

I am using it to control 7-segment displays like these:
 - [8-digit complete board](https://www.aliexpress.com/item/MAX7219-CWG-8-Digit-Digital-Tube-Display-Control-Module-Red-Three-IO-for/32815741807.html?spm=a2g0s.9042311.0.0.t2ISFz)
 - [6-digit clock display](https://www.aliexpress.com/item/0-36inch-6digits-red-clock-7-segment-led-display-3662AS-3662BS-10pcs/32793418781.html?spm=a2g0s.9042311.0.0.BL67Qr)

This pull request adds three new functions (and an example):
 - void setScanLimit(uint8_t level);
    Useful when the display has less than 8 digits.
 - void setDecode(uint8_t mask);
    Makes it really easy to display numbers on the 7-segment displays.
 - void setDigit(uint16_t digit, uint8_t value, bool dot = false);
    Makes it possible to set a single digit in the frameBuffer.

I hope you find it useful.

Best regards, Søren.

### CODE REVIEW

**Comment by bartoszbielawski** [comment]
Hi Søren,

I have checked your code and it looks fine. Before I merge it I have one question to ask.

Could you tell me why did you device to use my library in place of the standard one? I've optimized mine to be able to run multiple modules as a single display. I never had problems with refresh rate when using single displays (such as this 8x7seg or the clock display). My biggest setup is 8x(8x8) with 50 ms refresh rate and on that one I could see the lag.

Regards,
Bartosz

**Comment by Sthing** [comment]
Hi Bartosz,

Thank you for replying.

I am not sure which library you refer to as "the standard one". I have used https://github.com/wayoda/LedControl before, but it does not compile for the ESP8266 without a patch.

I also liked that your library used hardware SPI and the MIT License.

/Thing

**Comment by bartoszbielawski** [comment]
Yes, I consider LedMatrix to be the default one. I have used it before I got tired of the slowness. Must have patched it myself or they broke it after I have stopped using it. 

Well, okay. I'm wasn't preparing a release so while I will merge this the version may stay the same for some time.

Cheers,
Bartosz

**Comment by Sthing** [comment]
Thanks!

**Pull request merged**
