### PR TITLE
Add the reverse_display option to each example

### PR DESCRIPTION
**Pull request by scottchiefbaker**
I also converted the line endings on MarqueeTextClean to unix to be consistent with all the others. It *looks* like a huge change but it's just the line endings. Best viewed with `git diff -w`

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
I bought a matrix off of Ebay and had all kinds of problems with it until I found the "hidden" option of reverse on the `LEDMatrixDriver` constructor. This PR just adds a variable to expose that to each example.

Hopefully this will save someone some troubleshooting in the future.

**Comment by bartoszbielawski** [comment]
Hi, I'm currently reviewing a pull request from another contributor that has some extra code for the display reversal. That guy just added this "hidden" option and I want to be done with his PR before I start merging code that uses it. It probably means your code will have to be changed. Please wait a bit, I will get back to you.

**Comment by scottchiefbaker** [comment]
:+1: 

Sounds good

**Comment by bartoszbielawski** [comment]
Hi, I've pushed a new commit into the second branch. It contains updated code for the display reversal. I will make it an official release if testers (would you be willing to check the code?) won't find any problems. I think it would be good if you made a PR based on that branch/commit (or just wait till I merge it into master).

**Pull request closed without merging**
